//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Co_Op_Swift.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Co_Op_Swift.Resources.SqlStrings", typeof(SqlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SprintTasks(SprintID, Task_ID)
        ///VALUES ({0}, {1});.
        /// </summary>
        internal static string AddToLinkingTable {
            get {
                return ResourceManager.GetString("AddToLinkingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Proj_ID
        ///FROM Projects
        ///WHERE Title = &apos;{0}&apos;;.
        /// </summary>
        internal static string GetPid {
            get {
                return ResourceManager.GetString("GetPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(SprintID)
        ///FROM Sprints;.
        /// </summary>
        internal static string GetSprintId {
            get {
                return ResourceManager.GetString("GetSprintId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM Sprints
        ///INNER JOIN ProjectSprints
        ///ON Sprints.SprintID = ProjectSprints.SprintID
        ///WHERE ProjectSprints.Proj_ID = {0};.
        /// </summary>
        internal static string GetSprintPlans {
            get {
                return ResourceManager.GetString("GetSprintPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TaskDetail
        ///FROM TaskTable
        ///WHERE TaskName = &apos;{0}&apos;;.
        /// </summary>
        internal static string GetTaskDetail {
            get {
                return ResourceManager.GetString("GetTaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Task_ID
        ///FROM TaskTable
        ///WHERE TaskName = &apos;{0}&apos;
        ///AND TaskDetail = &apos;{1}&apos;;.
        /// </summary>
        internal static string GetTaskId {
            get {
                return ResourceManager.GetString("GetTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TaskTable.TaskName
        ///FROM TaskTable
        ///INNER JOIN SprintTasks
        ///ON TaskTable.Task_ID = SprintTasks.Task_ID
        ///WHERE SprintTasks.SprintID = {0};.
        /// </summary>
        internal static string GetTasks {
            get {
                return ResourceManager.GetString("GetTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ProjectSprints(Proj_ID, SprintID)
        ///VALUES ({0}, {1});.
        /// </summary>
        internal static string InsertProjectSprintTable {
            get {
                return ResourceManager.GetString("InsertProjectSprintTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Sprints(StartDate, EndDate)
        ///VALUES (&apos;{0}&apos;, &apos;{1}&apos;);.
        /// </summary>
        internal static string InsertSprintTable {
            get {
                return ResourceManager.GetString("InsertSprintTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TaskTable(UID, PID, TaskName, TaskDetail, Completed)
        ///VALUES ({3}, {2}, &apos;{0}&apos;, &apos;{1}&apos;, 0);.
        /// </summary>
        internal static string InsertTaskTable {
            get {
                return ResourceManager.GetString("InsertTaskTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Sprints.SprintID, StartDate, EndDate
        ///FROM Sprints
        ///INNER JOIN ProjectSprints
        ///ON Sprints.SprintID = ProjectSprints.SprintID
        ///WHERE ProjectSPrints.Proj_ID = {0};.
        /// </summary>
        internal static string LoadReleasePlan {
            get {
                return ResourceManager.GetString("LoadReleasePlan", resourceCulture);
            }
        }
    }
}
